### ISSUE TITLE
Icons arent loading/showup

### ISSUE THREAD

**Issue by Ryan-Mirch** [rakugoteam/Godot-Material-Icons#1]
The plugin appears to work, but there are no icons. Sorry if im being stupid but i have no idea what to do.

![image](https://user-images.githubusercontent.com/23248304/134461045-38b96006-1dfb-46bf-a11d-6143086a4ac7.png)
![image](https://user-images.githubusercontent.com/23248304/134461077-9cd53596-d0a3-4c03-9b74-9f8aa8d106ff.png)
![image](https://user-images.githubusercontent.com/23248304/134461100-c0f107b6-ced6-4b90-94b3-18082972aea2.png)

**Comment by Jeremi360** [comment]
@Ryan-Mirch
So I found that this bug that icon can don't show up on button, if `Button` has `text_clip` set to `true`.
I will fix it soon. Also, you use version **1.0** probably from **Godot's Asset-Lib**.
I don't recommend this - it takes long time to get Asset/Plugin updated there.
In case of icons doesn't show up on **MaterialIcon**, I already fixed it 1.1
Better is downloading [release](https://github.com/rakugoteam/Godot-Material-Icons/releases) from repo itself.

**Comment by Jeremi360** [comment]
@Ryan-Mirch
This new [Release](https://github.com/rakugoteam/Godot-Material-Icons/releases/tag/1.2) fix those bugs you have.

**Comment by Ryan-Mirch** [comment]
Awesome ty! Ill try the new release
