### ISSUE TITLE
No icons for android

### ISSUE THREAD

**Issue by Di4ik3r** [rakugoteam/Godot-Material-Icons#13]
**Describe the bug**
Published new update for my game, for iOS working well, but in android version - no icons provied.

**To Reproduce**
1. Try to run in android

**Expected behavior**
Icons to be there

**Screenshots**
<p align="center">
<img width="370" src="https://user-images.githubusercontent.com/48484651/187394339-20083259-8761-4430-b457-2ad16cdbfa54.png" />
<img width="320" src="https://user-images.githubusercontent.com/48484651/187394491-ea9f9a0a-79f4-413f-9514-a11e2885c2e6.jpg" />
</p>

**Runtime (please complete the following information):**
 - Godot version 3.5

**Comment by Jeremi360** [comment]
@Di4ik3r 

If you use version from AssetLib please switch to this one - verion on asset lib is outdated

Please check your export settings you need to add `*.json` files to included godot,
 by default skips them on export it is probably this - I wrote about this in repo Readme.
![]( https://github.com/rakugoteam/Godot-Material-Icons/raw/main/screenshot_export.png)

**Comment by Di4ik3r** [comment]
@Jeremi360 thanks! I'll try it! Sorry, I missed repo Readme
