### ISSUE TITLE
How to upgrade Material_design_icons version

### ISSUE THREAD

**Issue by aiaimimi0920** [rakugoteam/Godot-Material-Icons#16]
Thank you for creating this project.

What I would like to inquire about is:

If I want to upgrade to the "Material_design_icons. ttf" version, 
where should I download it? I haven't find it in "https://pictogrammers.com/"
Can you help me find the link to download ttf?

**Comment by Jeremi360** [comment]
> Thank you for creating this project.
Is nice to hear that.

So I don't use https://pictogrammers.com/ - as it is impossible to download ttf from there.
I use https://github.com/templarian/MaterialDesign - and I write about it in [Readme](https://github.com/rakugoteam/Godot-Material-Icons/blob/godot-4/README.md).
So here is newest font: 
https://github.com/Templarian/MaterialDesign-Webfont/blob/master/fonts/materialdesignicons-webfont.ttf
But downloading only it will and replace it doesn't add you new icons.
I need updated json to to have new icons names.
And I can generate one using this file:
https://github.com/Templarian/MaterialDesign-Webfont/blob/master/css/materialdesignicons.css
I will soon add python script that will make easy to update this 2 files.
The I use similar approach in my emojis-for-godot project.

**Comment by aiaimimi0920** [comment]
Thank you very much for your prompt reply. Thank you. 
Thank you again for this project

**Comment by Jeremi360** [comment]
continued as #17

**Comment by Jeremi360** [comment]
Hi, @aiaimimi0920 !
I was busy by other stuff, but here you have the pre-release of this addon: [**material-design-icons.zip**](https://github.com/rakugoteam/Godot-Material-Icons/files/14136061/material-design-icons.zip)

Why pre-release ? - I want to add doc comments, online docs, and easy way to open online docs from godot.

**Comment by aiaimimi0920** [comment]
thanks your help
